name: chesapeake_mhw_2021dask
channels:
  - conda-forge
dependencies:
  # Required for full project functionality (dont remove)
  - pytest
  # Examples (remove and add as needed)
  - jupyter
  - jupyterlab
  - xarray
  - numpy
  - scipy
  - dask=2021.10.0
  - netcdf4
  - zarr
  - pydap
  - lxml
  - requests
  - aiohttp
  - pandas
  - matplotlib
  - seaborn
  - cartopy
